<?php

namespace App\Enums\Common;

enum Country: string
{
    case AFGHANISTAN = 'AFG';
    case ALAND_ISLANDS = 'ALA';
    case ALBANIA = 'ALB';
    case ALGERIA = 'DZA';
    case AMERICAN_SAMOA = 'ASM';
    case ANDORRA = 'AND';
    case ANGOLA = 'AGO';
    case ANGUILLA = 'AIA';
    case ANTARCTICA = 'ATA';
    case ANTIGUA_AND_BARBUDA = 'ATG';
    case ARGENTINA = 'ARG';
    case ARMENIA = 'ARM';
    case ARUBA = 'ABW';
    case AUSTRALIA = 'AUS';
    case AUSTRIA = 'AUT';
    case AZERBAIJAN = 'AZE';
    case BAHAMAS = 'BHS';
    case BAHRAIN = 'BHR';
    case BANGLADESH = 'BGD';
    case BARBADOS = 'BRB';
    case BELARUS = 'BLR';
    case BELGIUM = 'BEL';
    case BELIZE = 'BLZ';
    case BENIN = 'BEN';
    case BERMUDA = 'BMU';
    case BHUTAN = 'BTN';
    case BOLIVIA = 'BOL';
    case BONAIRE_SINT_EUSTATIUS_AND_SABA = 'BES';
    case BOSNIA_AND_HERZEGOVINA = 'BIH';
    case BOTSWANA = 'BWA';
    case BOUVET_ISLAND = 'BVT';
    case BRAZIL = 'BRA';
    case BRITISH_INDIAN_OCEAN_TERRITORY = 'IOT';
    case BRITISH_VIRGIN_ISLANDS = 'VGB';
    case BRUNEI = 'BRN';
    case BULGARIA = 'BGR';
    case BURKINA_FASO = 'BFA';
    case BURUNDI = 'BDI';
    case CABO_VERDE = 'CPV';
    case CAMBODIA = 'KHM';
    case CAMEROON = 'CMR';
    case CANADA = 'CAN';
    case CAYMAN_ISLANDS = 'CYM';
    case CENTRAL_AFRICAN_REPUBLIC = 'CAF';
    case CHAD = 'TCD';
    case CHILE = 'CHL';
    case CHINA = 'CHN';
    case CHRISTMAS_ISLAND = 'CXR';
    case COCOS_KEELING_ISLANDS = 'CCK';
    case COLOMBIA = 'COL';
    case COMOROS = 'COM';
    case CONGO = 'COG';
    case COOK_ISLANDS = 'COK';
    case COSTA_RICA = 'CRI';
    case COTE_DIVOIRE = 'CIV';
    case CROATIA = 'HRV';
    case CUBA = 'CUB';
    case CURACAO = 'CUW';
    case CYPRUS = 'CYP';
    case CZECHIA = 'CZE';
    case DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'COD';
    case DENMARK = 'DNK';
    case DJIBOUTI = 'DJI';
    case DOMINICA = 'DMA';
    case DOMINICAN_REPUBLIC = 'DOM';
    case ECUADOR = 'ECU';
    case EGYPT = 'EGY';
    case EL_SALVADOR = 'SLV';
    case EQUATORIAL_GUINEA = 'GNQ';
    case ERITREA = 'ERI';
    case ESTONIA = 'EST';
    case ESWATINI = 'SWZ';
    case ETHIOPIA = 'ETH';
    case FALKLAND_ISLANDS = 'FLK';
    case FAROE_ISLANDS = 'FRO';
    case FIJI = 'FJI';
    case FINLAND = 'FIN';
    case FRANCE = 'FRA';
    case FRENCH_GUIANA = 'GUF';
    case FRENCH_POLYNESIA = 'PYF';
    case FRENCH_SOUTHERN_TERRITORIES = 'ATF';
    case GABON = 'GAB';
    case GAMBIA = 'GMB';
    case GEORGIA = 'GEO';
    case GERMANY = 'DEU';
    case GHANA = 'GHA';
    case GIBRALTAR = 'GIB';
    case GREECE = 'GRC';
    case GREENLAND = 'GRL';
    case GRENADA = 'GRD';
    case GUADELOUPE = 'GLP';
    case GUAM = 'GUM';
    case GUATEMALA = 'GTM';
    case GUERNSEY = 'GGY';
    case GUINEA = 'GIN';
    case GUINEA_BISSAU = 'GNB';
    case GUYANA = 'GUY';
    case HAITI = 'HTI';
    case HEARD_ISLAND_AND_MCDONALD_ISLANDS = 'HMD';
    case HONDURAS = 'HND';
    case HONG_KONG = 'HKG';
    case HUNGARY = 'HUN';
    case ICELAND = 'ISL';
    case INDIA = 'IND';
    case INDONESIA = 'IDN';
    case IRAN = 'IRN';
    case IRAQ = 'IRQ';
    case IRELAND = 'IRL';
    case ISLE_OF_MAN = 'IMN';
    case ISRAEL = 'ISR';
    case ITALY = 'ITA';
    case JAMAICA = 'JAM';
    case JAPAN = 'JPN';
    case JERSEY = 'JEY';
    case JORDAN = 'JOR';
    case KAZAKHSTAN = 'KAZ';
    case KENYA = 'KEN';
    case KIRIBATI = 'KIR';
    case KUWAIT = 'KWT';
    case KYRGYZSTAN = 'KGZ';
    case LAOS = 'LAO';
    case LATVIA = 'LVA';
    case LEBANON = 'LBN';
    case LESOTHO = 'LSO';
    case LIBERIA = 'LBR';
    case LIBYA = 'LBY';
    case LIECHTENSTEIN = 'LIE';
    case LITHUANIA = 'LTU';
    case LUXEMBOURG = 'LUX';
    case MACAO = 'MAC';
    case MADAGASCAR = 'MDG';
    case MALAWI = 'MWI';
    case MALAYSIA = 'MYS';
    case MALDIVES = 'MDV';
    case MALI = 'MLI';
    case MALTA = 'MLT';
    case MARSHALL_ISLANDS = 'MHL';
    case MARTINIQUE = 'MTQ';
    case MAURITANIA = 'MRT';
    case MAURITIUS = 'MUS';
    case MAYOTTE = 'MYT';
    case MEXICO = 'MEX';
    case MICRONESIA = 'FSM';
    case MOLDOVA = 'MDA';
    case MONACO = 'MCO';
    case MONGOLIA = 'MNG';
    case MONTENEGRO = 'MNE';
    case MONTSERRAT = 'MSR';
    case MOROCCO = 'MAR';
    case MOZAMBIQUE = 'MOZ';
    case MYANMAR = 'MMR';
    case NAMIBIA = 'NAM';
    case NAURU = 'NRU';
    case NEPAL = 'NPL';
    case NETHERLANDS = 'NLD';
    case NEW_CALEDONIA = 'NCL';
    case NEW_ZEALAND = 'NZL';
    case NICARAGUA = 'NIC';
    case NIGER = 'NER';
    case NIGERIA = 'NGA';
    case NIUE = 'NIU';
    case NORFOLK_ISLAND = 'NFK';
    case NORTHERN_MARIANA_ISLANDS = 'MNP';
    case NORTH_KOREA = 'PRK';
    case NORTH_MACEDONIA = 'MKD';
    case NORWAY = 'NOR';
    case OMAN = 'OMN';
    case PAKISTAN = 'PAK';
    case PALAU = 'PLW';
    case PALESTINE = 'PSE';
    case PANAMA = 'PAN';
    case PAPUA_NEW_GUINEA = 'PNG';
    case PARAGUAY = 'PRY';
    case PERU = 'PER';
    case PHILIPPINES = 'PHL';
    case PITCAIRN = 'PCN';
    case POLAND = 'POL';
    case PORTUGAL = 'PRT';
    case PUERTO_RICO = 'PRI';
    case QATAR = 'QAT';
    case REUNION = 'REU';
    case ROMANIA = 'ROU';
    case RUSSIAN_FEDERATION = 'RUS';
    case RWANDA = 'RWA';
    case SAINT_BARTHELEMY = 'BLM';
    case SAINT_HELENA = 'SHN';
    case SAINT_KITTS_AND_NEVIS = 'KNA';
    case SAINT_LUCIA = 'LCA';
    case SAINT_MARTIN = 'MAF';
    case SAINT_PIERRE_AND_MIQUELON = 'SPM';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'VCT';
    case SAMOA = 'WSM';
    case SAN_MARINO = 'SMR';
    case SAO_TOME_AND_PRINCIPE = 'STP';
    case SAUDI_ARABIA = 'SAU';
    case SENEGAL = 'SEN';
    case SERBIA = 'SRB';
    case SEYCHELLES = 'SYC';
    case SIERRA_LEONE = 'SLE';
    case SINGAPORE = 'SGP';
    case SINT_MAARTEN = 'SXM';
    case SLOVAKIA = 'SVK';
    case SLOVENIA = 'SVN';
    case SOLOMON_ISLANDS = 'SLB';
    case SOMALIA = 'SOM';
    case SOUTH_AFRICA = 'ZAF';
    case SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 'SGS';
    case SOUTH_KOREA = 'KOR';
    case SOUTH_SUDAN = 'SSD';
    case SPAIN = 'ESP';
    case SRI_LANKA = 'LKA';
    case SUDAN = 'SDN';
    case SURINAME = 'SUR';
    case SVALBARD_AND_JAN_MAYEN = 'SJM';
    case SWEDEN = 'SWE';
    case SWITZERLAND = 'CHE';
    case SYRIA = 'SYR';
    case TAJIKISTAN = 'TJK';
    case TANZANIA = 'TZA';
    case THAILAND = 'THA';
    case TIMOR_LESTE = 'TLS';
    case TOGO = 'TGO';
    case TOKELAU = 'TKL';
    case TONGA = 'TON';
    case TRINIDAD_AND_TOBAGO = 'TTO';
    case TUNISIA = 'TUN';
    case TURKEY = 'TUR';
    case TURKMENISTAN = 'TKM';
    case TURKS_AND_CAICOS_ISLANDS = 'TCA';
    case TUVALU = 'TUV';
    case UGANDA = 'UGA';
    case UKRAINE = 'UKR';
    case UNITED_ARAB_EMIRATES = 'ARE';
    case UNITED_KINGDOM = 'GBR';
    case UNITED_STATES = 'USA';
    case UNITED_STATES_MINOR_OUTLYING_ISLANDS = 'UMI';
    case UNITED_STATES_VIRGIN_ISLANDS = 'VIR';
    case URUGUAY = 'URY';
    case UZBEKISTAN = 'UZB';
    case VANUATU = 'VUT';
    case VATICAN_CITY = 'VAT';
    case VENEZUELA = 'VEN';
    case VIETNAM = 'VNM';
    case WALLIS_AND_FUTUNA_ISLANDS = 'WLF';
    case WESTERN_SAHARA = 'ESH';
    case YEMEN = 'YEM';
    case ZAMBIA = 'ZMB';
    case ZIMBABWE = 'ZWE';

    public function label(): string
    {
        return match ($this) {
            self::AFGHANISTAN => 'Afghanistan',
            self::ALAND_ISLANDS => 'Åland Islands',
            self::ALBANIA => 'Albania',
            self::ALGERIA => 'Algeria',
            self::AMERICAN_SAMOA => 'American Samoa',
            self::ANDORRA => 'Andorra',
            self::ANGOLA => 'Angola',
            self::ANGUILLA => 'Anguilla',
            self::ANTARCTICA => 'Antarctica',
            self::ANTIGUA_AND_BARBUDA => 'Antigua and Barbuda',
            self::ARGENTINA => 'Argentina',
            self::ARMENIA => 'Armenia',
            self::ARUBA => 'Aruba',
            self::AUSTRALIA => 'Australia',
            self::AUSTRIA => 'Austria',
            self::AZERBAIJAN => 'Azerbaijan',
            self::BAHAMAS => 'Bahamas',
            self::BAHRAIN => 'Bahrain',
            self::BANGLADESH => 'Bangladesh',
            self::BARBADOS => 'Barbados',
            self::BELARUS => 'Belarus',
            self::BELGIUM => 'Belgium',
            self::BELIZE => 'Belize',
            self::BENIN => 'Benin',
            self::BERMUDA => 'Bermuda',
            self::BHUTAN => 'Bhutan',
            self::BOLIVIA => 'Bolivia',
            self::BONAIRE_SINT_EUSTATIUS_AND_SABA => 'Bonaire, Sint Eustatius and Saba',
            self::BOSNIA_AND_HERZEGOVINA => 'Bosnia and Herzegovina',
            self::BOTSWANA => 'Botswana',
            self::BOUVET_ISLAND => 'Bouvet Island',
            self::BRAZIL => 'Brazil',
            self::BRITISH_INDIAN_OCEAN_TERRITORY => 'British Indian Ocean Territory',
            self::BRITISH_VIRGIN_ISLANDS => 'British Virgin Islands',
            self::BRUNEI => 'Brunei',
            self::BULGARIA => 'Bulgaria',
            self::BURKINA_FASO => 'Burkina Faso',
            self::BURUNDI => 'Burundi',
            self::CABO_VERDE => 'Cabo Verde',
            self::CAMBODIA => 'Cambodia',
            self::CAMEROON => 'Cameroon',
            self::CANADA => 'Canada',
            self::CAYMAN_ISLANDS => 'Cayman Islands',
            self::CENTRAL_AFRICAN_REPUBLIC => 'Central African Republic',
            self::CHAD => 'Chad',
            self::CHILE => 'Chile',
            self::CHINA => 'China',
            self::CHRISTMAS_ISLAND => 'Christmas Island',
            self::COCOS_KEELING_ISLANDS => 'Cocos (Keeling) Islands',
            self::COLOMBIA => 'Colombia',
            self::COMOROS => 'Comoros',
            self::CONGO => 'Congo',
            self::COOK_ISLANDS => 'Cook Islands',
            self::COSTA_RICA => 'Costa Rica',
            self::COTE_DIVOIRE => 'Côte d’Ivoire',
            self::CROATIA => 'Croatia',
            self::CUBA => 'Cuba',
            self::CURACAO => 'Curaçao',
            self::CYPRUS => 'Cyprus',
            self::CZECHIA => 'Czechia',
            self::DEMOCRATIC_REPUBLIC_OF_THE_CONGO => 'Democratic Republic of the Congo',
            self::DENMARK => 'Denmark',
            self::DJIBOUTI => 'Djibouti',
            self::DOMINICA => 'Dominica',
            self::DOMINICAN_REPUBLIC => 'Dominican Republic',
            self::ECUADOR => 'Ecuador',
            self::EGYPT => 'Egypt',
            self::EL_SALVADOR => 'El Salvador',
            self::EQUATORIAL_GUINEA => 'Equatorial Guinea',
            self::ERITREA => 'Eritrea',
            self::ESTONIA => 'Estonia',
            self::ESWATINI => 'Eswatini',
            self::ETHIOPIA => 'Ethiopia',
            self::FALKLAND_ISLANDS => 'Falkland Islands (Malvinas)',
            self::FAROE_ISLANDS => 'Faroe Islands',
            self::FIJI => 'Fiji',
            self::FINLAND => 'Finland',
            self::FRANCE => 'France',
            self::FRENCH_GUIANA => 'French Guiana',
            self::FRENCH_POLYNESIA => 'French Polynesia',
            self::FRENCH_SOUTHERN_TERRITORIES => 'French Southern Territories',
            self::GABON => 'Gabon',
            self::GAMBIA => 'Gambia',
            self::GEORGIA => 'Georgia',
            self::GERMANY => 'Germany',
            self::GHANA => 'Ghana',
            self::GIBRALTAR => 'Gibraltar',
            self::GREECE => 'Greece',
            self::GREENLAND => 'Greenland',
            self::GRENADA => 'Grenada',
            self::GUADELOUPE => 'Guadeloupe',
            self::GUAM => 'Guam',
            self::GUATEMALA => 'Guatemala',
            self::GUERNSEY => 'Guernsey',
            self::GUINEA => 'Guinea',
            self::GUINEA_BISSAU => 'Guinea-Bissau',
            self::GUYANA => 'Guyana',
            self::HAITI => 'Haiti',
            self::HEARD_ISLAND_AND_MCDONALD_ISLANDS => 'Heard Island and McDonald Islands',
            self::HONDURAS => 'Honduras',
            self::HONG_KONG => 'China, Hong Kong Special Administrative Region',
            self::HUNGARY => 'Hungary',
            self::ICELAND => 'Iceland',
            self::INDIA => 'India',
            self::INDONESIA => 'Indonesia',
            self::IRAN => 'Iran',
            self::IRAQ => 'Iraq',
            self::IRELAND => 'Ireland',
            self::ISLE_OF_MAN => 'Isle of Man',
            self::ISRAEL => 'Israel',
            self::ITALY => 'Italy',
            self::JAMAICA => 'Jamaica',
            self::JAPAN => 'Japan',
            self::JERSEY => 'Jersey',
            self::JORDAN => 'Jordan',
            self::KAZAKHSTAN => 'Kazakhstan',
            self::KENYA => 'Kenya',
            self::KIRIBATI => 'Kiribati',
            self::KUWAIT => 'Kuwait',
            self::KYRGYZSTAN => 'Kyrgyzstan',
            self::LAOS => 'Laos',
            self::LATVIA => 'Latvia',
            self::LEBANON => 'Lebanon',
            self::LESOTHO => 'Lesotho',
            self::LIBERIA => 'Liberia',
            self::LIBYA => 'Libya',
            self::LIECHTENSTEIN => 'Liechtenstein',
            self::LITHUANIA => 'Lithuania',
            self::LUXEMBOURG => 'Luxembourg',
            self::MACAO => 'China, Macao Special Administrative Region',
            self::MADAGASCAR => 'Madagascar',
            self::MALAWI => 'Malawi',
            self::MALAYSIA => 'Malaysia',
            self::MALDIVES => 'Maldives',
            self::MALI => 'Mali',
            self::MALTA => 'Malta',
            self::MARSHALL_ISLANDS => 'Marshall Islands',
            self::MARTINIQUE => 'Martinique',
            self::MAURITANIA => 'Mauritania',
            self::MAURITIUS => 'Mauritius',
            self::MAYOTTE => 'Mayotte',
            self::MEXICO => 'Mexico',
            self::MICRONESIA => 'Micronesia',
            self::MOLDOVA => 'Moldova',
            self::MONACO => 'Monaco',
            self::MONGOLIA => 'Mongolia',
            self::MONTENEGRO => 'Montenegro',
            self::MONTSERRAT => 'Montserrat',
            self::MOROCCO => 'Morocco',
            self::MOZAMBIQUE => 'Mozambique',
            self::MYANMAR => 'Myanmar',
            self::NAMIBIA => 'Namibia',
            self::NAURU => 'Nauru',
            self::NEPAL => 'Nepal',
            self::NETHERLANDS => 'Netherlands',
            self::NEW_CALEDONIA => 'New Caledonia',
            self::NEW_ZEALAND => 'New Zealand',
            self::NICARAGUA => 'Nicaragua',
            self::NIGER => 'Niger',
            self::NIGERIA => 'Nigeria',
            self::NIUE => 'Niue',
            self::NORFOLK_ISLAND => 'Norfolk Island',
            self::NORTHERN_MARIANA_ISLANDS => 'Northern Mariana Islands',
            self::NORTH_KOREA => 'North Korea',
            self::NORTH_MACEDONIA => 'North Macedonia',
            self::NORWAY => 'Norway',
            self::OMAN => 'Oman',
            self::PAKISTAN => 'Pakistan',
            self::PALAU => 'Palau',
            self::PALESTINE => 'State of Palestine',
            self::PANAMA => 'Panama',
            self::PAPUA_NEW_GUINEA => 'Papua New Guinea',
            self::PARAGUAY => 'Paraguay',
            self::PERU => 'Peru',
            self::PHILIPPINES => 'Philippines',
            self::PITCAIRN => 'Pitcairn',
            self::POLAND => 'Poland',
            self::PORTUGAL => 'Portugal',
            self::PUERTO_RICO => 'Puerto Rico',
            self::QATAR => 'Qatar',
            self::REUNION => 'Réunion',
            self::ROMANIA => 'Romania',
            self::RUSSIAN_FEDERATION => 'Russian Federation',
            self::RWANDA => 'Rwanda',
            self::SAINT_BARTHELEMY => 'Saint Barthélemy',
            self::SAINT_HELENA => 'Saint Helena',
            self::SAINT_KITTS_AND_NEVIS => 'Saint Kitts and Nevis',
            self::SAINT_LUCIA => 'Saint Lucia',
            self::SAINT_MARTIN => 'Saint Martin (French Part)',
            self::SAINT_PIERRE_AND_MIQUELON => 'Saint Pierre and Miquelon',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'Saint Vincent and the Grenadines',
            self::SAMOA => 'Samoa',
            self::SAN_MARINO => 'San Marino',
            self::SAO_TOME_AND_PRINCIPE => 'Sao Tome and Principe',
            self::SAUDI_ARABIA => 'Saudi Arabia',
            self::SENEGAL => 'Senegal',
            self::SERBIA => 'Serbia',
            self::SEYCHELLES => 'Seychelles',
            self::SIERRA_LEONE => 'Sierra Leone',
            self::SINGAPORE => 'Singapore',
            self::SINT_MAARTEN => 'Sint Maarten (Dutch part)',
            self::SLOVAKIA => 'Slovakia',
            self::SLOVENIA => 'Slovenia',
            self::SOLOMON_ISLANDS => 'Solomon Islands',
            self::SOMALIA => 'Somalia',
            self::SOUTH_AFRICA => 'South Africa',
            self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => 'South Georgia and the South Sandwich Islands',
            self::SOUTH_KOREA => 'South Korea',
            self::SOUTH_SUDAN => 'South Sudan',
            self::SPAIN => 'Spain',
            self::SRI_LANKA => 'Sri Lanka',
            self::SUDAN => 'Sudan',
            self::SURINAME => 'Suriname',
            self::SVALBARD_AND_JAN_MAYEN => 'Svalbard and Jan Mayen Islands',
            self::SWEDEN => 'Sweden',
            self::SWITZERLAND => 'Switzerland',
            self::SYRIA => 'Syria',
            self::TAJIKISTAN => 'Tajikistan',
            self::TANZANIA => 'Tanzania',
            self::THAILAND => 'Thailand',
            self::TIMOR_LESTE => 'Timor-Leste',
            self::TOGO => 'Togo',
            self::TOKELAU => 'Tokelau',
            self::TONGA => 'Tonga',
            self::TRINIDAD_AND_TOBAGO => 'Trinidad and Tobago',
            self::TUNISIA => 'Tunisia',
            self::TURKEY => 'Turkey',
            self::TURKMENISTAN => 'Turkmenistan',
            self::TURKS_AND_CAICOS_ISLANDS => 'Turks and Caicos Islands',
            self::TUVALU => 'Tuvalu',
            self::UGANDA => 'Uganda',
            self::UKRAINE => 'Ukraine',
            self::UNITED_ARAB_EMIRATES => 'United Arab Emirates',
            self::UNITED_KINGDOM => 'United Kingdom',
            self::UNITED_STATES => 'United States',
            self::UNITED_STATES_MINOR_OUTLYING_ISLANDS => 'United States Minor Outlying Islands',
            self::UNITED_STATES_VIRGIN_ISLANDS => 'United States Virgin Islands',
            self::URUGUAY => 'Uruguay',
            self::UZBEKISTAN => 'Uzbekistan',
            self::VANUATU => 'Vanuatu',
            self::VATICAN_CITY => 'Vatican City',
            self::VENEZUELA => 'Venezuela',
            self::VIETNAM => 'Vietnam',
            self::WALLIS_AND_FUTUNA_ISLANDS => 'Wallis and Futuna Islands',
            self::WESTERN_SAHARA => 'Western Sahara',
            self::YEMEN => 'Yemen',
            self::ZAMBIA => 'Zambia',
            self::ZIMBABWE => 'Zimbabwe',
        };
    }

    public static function getOptions(): array
    {
        return array_map(
            fn($case) => ['value' => $case->value, 'label' => $case->label()],
            self::cases()
        );
    }

    public static function getLabelByValue(string $value): ?string
    {
        $country = self::tryFrom($value);
        return $country?->label();
    }
}
